### ISSUE TITLE
Deployment fails for pipeline with single element in an array after update of properties

### ISSUE THREAD

**Issue by lidroz** [Azure-Player/azure.synapse.tools#15]
Hi again Kamil, new customer for me and new use case for your great tool :).
I've got an error (Exception has been thrown by the target of an invocation) from Set-AzSynapsePipeline for a pipeline where I replace properties with Stage parameter. By comparing the pipeline before and after the replacement I found out that "activities" with only one child activity was missing [] in the final json file. In my case it was an foreach activity with only one child but the same error happens in a simple pipeline with one activity. 
I googled a bit on ConvertTo-Json which seems to have this bug of treating arrays with single elements wrongly. But -Depth parameter should have resolved this error. So I figured my "activities" should be converted to array earlier. Since PowerShell is not my strongest side the solution became a foolish fix in form of the following code:
$arr = @()
$arr += $Item.$prop
$Item.$prop = $arr

in ConvertFrom-OrderedHashTablesToArrays in the end of if ($Item.$prop.GetType().Name -eq "OrderedDictionary") statement. You will surely find a more elegant fix.

Here is a test pipeline:
`{
    "name": "TestSingleActivity",
    "properties": {
        "activities": [
            {
                "name": "Set variable1",
                "type": "SetVariable",
                "dependsOn": [],
                "userProperties": [],
                "typeProperties": {
                    "variableName": "TestVariable",
                    "value": "1"
                }
            }
        ],
        "variables": {
            "TestVariable": {
                "type": "String",
                "defaultValue": "test"
            }
        },
        "annotations": []
    }
}`

And a test config file:
type,name,path,value
pipeline,TestSingleActivity,variables.TestVariable.defaultValue,"test1"

**Comment by simonp92** [comment]
@NowinskiK  I am experiencing this problem as well. Let me know if anything needs to be elaborated

**Comment by mikegoatly** [comment]
Thanks for merging, @NowinskiK!

**Comment by NowinskiK** [comment]
Thanks for contributing. You're always welcome to do more.
