### ISSUE TITLE
Delete not in source

### ISSUE THREAD

**Issue by LiquoriChris** [Azure-Player/azure.synapse.tools#27]
Hello,

I was trying to use the option `DeleteNotInSource`, but it does not look like the option is being applied to the publish step in Synapse. Can you please add that as a part of the `Publish-AzSynapseFromJson` function?

Thanks.

**Comment by LiquoriChris** [comment]
@NowinskiK I am in the process of replicating the option the same that is in the `azure.datafactory.tools`. Will submit a pr shortly.

**Comment by NowinskiK** [comment]
close #28
